apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.service.name }}-helm
  labels:
    app: {{ .Values.service.name }}
spec:
  replicas: {{ .Values.replicaCount }} # <-- 변수 사용!
  selector:
    matchLabels:
      app: {{ .Values.service.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.service.name }}
    spec:
      containers:
        - name: {{ .Values.service.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}" # <-- 변수 사용!
          ports:
            - containerPort: {{ .Values.service.port }} # <-- 변수 사용!
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "default"